Events data
CS546-group45-web/UInvite pull request #13
Opened 2022-12-06 18:24 UTC by Kvtran3546

2022-12-06 23:32 UTC, manisaiprasad commented on server/data/users.js
> +  hashed_password = await bcrypt.hash(password, 16);
Why this is chnaged

2022-12-06 23:35 UTC, manisaiprasad requested changes

2022-12-06 23:35 UTC, manisaiprasad commented on server/data/users.js
>      gender: gender,
Why is  this removed

2022-12-06 23:35 UTC, manisaiprasad commented on server/data/users.js
Why this is removed if this from merge conflicts make sure all changes from others are included

2022-12-13 00:28 UTC, SumanMohanty20012987 approved these changes
Had to make the following changes
Changes ->
	data/event.js:
		1)line 92->In getAllEvents
					return events -> return events_list
		2)line 103-> In getEventsByTitle:
					added ``
		3)line 106->const event = await eventCollection.findOne({ event_title: title }); changed key
						
						
	
	
	validation.js:
		1)line 32: throw `Title must only contain letters or numbers`
		2)line 34: if (input.length < 4) throw `${name} should be of length 4 or greater`;

2022-12-15 06:13 UTC, manisaiprasad approved these changes

2022-12-15 06:13 UTC, manisaiprasad commented on server/data/users.js
> +
```suggestion
```

2022-12-15 06:13 UTC, manisaiprasad commented on server/data/users.js
> +
```suggestion
```

2022-12-15 06:13 UTC, manisaiprasad commented on server/data/users.js
> +  }
```suggestion
```

2022-12-15 06:13 UTC, manisaiprasad commented on server/data/users.js
> +
duplicated getUserById_Object

2022-12-15 06:13 UTC, merged